"""Utilities for applying TimesFM 2.5 to financial OHLCVA data.

TimesFM 2.5 remains a univariate forecasting model. This module implements the
zero-shot workflow for financial data:

1. Validate and normalize OHLCVA frames.
2. Convert each symbol into a single target series such as close or returns.
3. Build future-known calendar covariates for TimesFM XReg.
4. Create holdout or rolling backtest tasks.
5. Flatten forecasts and compute evaluation metrics.

The helpers here intentionally do not assume future OHLCVA values are known.
Only future-known calendar covariates are generated by default.
"""

from __future__ import annotations

import dataclasses
import json
from pathlib import Path
from typing import Any, Literal, Sequence

import numpy as np
import pandas as pd

FinancialTarget = Literal[
  "close",
  "log_close",
  "close_return",
  "log_close_return",
  "hlc3",
  "ohlc4",
  "volume",
  "log_volume",
  "vwap",
]

_RETURN_EPS = 1e-8


@dataclasses.dataclass(frozen=True)
class OHLCVAColumns:
  """Schema for an OHLCVA-like dataframe."""

  time: str = "timestamp"
  symbol: str = "symbol"
  open: str = "open"
  high: str = "high"
  low: str = "low"
  close: str = "close"
  volume: str = "volume"
  amount: str | None = "amount"
  exchange: str | None = None


@dataclasses.dataclass(frozen=True)
class PreparedTask:
  """One TimesFM forecast task built from a single symbol window."""

  symbol: str
  target_name: FinancialTarget
  cutoff_time: pd.Timestamp
  context_values: np.ndarray
  context_timestamps: pd.DatetimeIndex
  future_timestamps: pd.DatetimeIndex
  future_values: np.ndarray | None
  dynamic_numerical_covariates: dict[str, np.ndarray]
  dynamic_categorical_covariates: dict[str, np.ndarray]
  static_numerical_covariates: dict[str, float]
  static_categorical_covariates: dict[str, int | str]
  frequency: str


@dataclasses.dataclass(frozen=True)
class PreparedTaskCollection:
  """A collection of forecast tasks plus skipped-symbol diagnostics."""

  tasks: list[PreparedTask]
  skipped_symbols: dict[str, str]


@dataclasses.dataclass(frozen=True)
class LoadedOHLCVAData:
  """Normalized OHLCVA dataframe plus file-level loading metadata."""

  frame: pd.DataFrame
  source_files: list[str]
  skipped_files: dict[str, str]


def _required_columns(columns: OHLCVAColumns) -> list[str]:
  required = [
    columns.time,
    columns.symbol,
    columns.open,
    columns.high,
    columns.low,
    columns.close,
    columns.volume,
  ]
  if columns.amount is not None:
    required.append(columns.amount)
  if columns.exchange is not None:
    required.append(columns.exchange)
  return required


def _parse_timestamp_series(values: pd.Series) -> pd.Series:
  """Parses common financial timestamp encodings into pandas timestamps."""

  string_values = values.astype(str).str.strip()
  string_values = string_values.str.replace(r"\.0$", "", regex=True)

  non_null = string_values[~values.isna()]
  if non_null.empty:
    return pd.to_datetime(values, utc=False, errors="coerce")

  if non_null.str.fullmatch(r"\d{8}").all():
    return pd.to_datetime(string_values, format="%Y%m%d", utc=False, errors="coerce")
  if non_null.str.fullmatch(r"\d{14}").all():
    return pd.to_datetime(
      string_values,
      format="%Y%m%d%H%M%S",
      utc=False,
      errors="coerce",
    )
  return pd.to_datetime(values, utc=False, errors="coerce")


def _normalize_raw_ohlcva_columns(frame: pd.DataFrame) -> pd.DataFrame:
  """Normalizes common financial CSV column aliases into the project schema."""

  rename_map = {}
  for column in frame.columns:
    cleaned = column.lstrip("\ufeff").strip()
    lower = cleaned.lower()
    if lower == "ts_code":
      rename_map[column] = "symbol"
    elif lower in {"trade_date", "date"}:
      rename_map[column] = "timestamp"
    elif lower == "vol":
      rename_map[column] = "volume"
    elif lower in {"amt", "turnover"}:
      rename_map[column] = "amount"
    elif lower in {"open", "high", "low", "close", "amount", "volume", "symbol", "timestamp"}:
      rename_map[column] = lower
  if rename_map:
    frame = frame.rename(columns=rename_map)
  return frame


def _load_single_ohlcva_csv(path: Path) -> pd.DataFrame:
  """Loads one OHLCVA CSV and infers missing symbol information when possible."""

  frame = pd.read_csv(path, encoding="utf-8-sig")
  frame = _normalize_raw_ohlcva_columns(frame)
  if "symbol" not in frame.columns:
    symbol = path.stem.split("_")[0]
    frame["symbol"] = symbol
  return frame


def load_ohlcva_input(
  input_path: str | Path,
  *,
  glob_pattern: str = "*.csv",
  skip_hidden_files: bool = True,
  skip_metadata_prefix: str = "_",
) -> LoadedOHLCVAData:
  """Loads one OHLCVA CSV or a directory of per-symbol CSV files.

  The loader is designed for common financial exports where each file stores one
  symbol and columns may be named `ts_code`, `trade_date`, and `vol`.
  """

  path = Path(input_path)
  if not path.exists():
    raise FileNotFoundError(f"Input path does not exist: {path}")

  source_files: list[str] = []
  skipped_files: dict[str, str] = {}

  if path.is_file():
    frame = _load_single_ohlcva_csv(path)
    return LoadedOHLCVAData(
      frame=frame,
      source_files=[str(path)],
      skipped_files=skipped_files,
    )

  frames = []
  for csv_path in sorted(path.glob(glob_pattern)):
    if csv_path.is_dir():
      continue
    if skip_hidden_files and csv_path.name.startswith("."):
      continue
    if skip_metadata_prefix and csv_path.name.startswith(skip_metadata_prefix):
      skipped_files[str(csv_path)] = "metadata or auxiliary file"
      continue
    try:
      frames.append(_load_single_ohlcva_csv(csv_path))
      source_files.append(str(csv_path))
    except Exception as exc:
      skipped_files[str(csv_path)] = str(exc)

  if not frames:
    raise ValueError(f"No OHLCVA CSV files were loaded from directory: {path}")

  frame = pd.concat(frames, ignore_index=True)
  return LoadedOHLCVAData(
    frame=frame,
    source_files=source_files,
    skipped_files=skipped_files,
  )


def validate_ohlcva_frame(df: pd.DataFrame, columns: OHLCVAColumns) -> pd.DataFrame:
  """Normalizes a raw OHLCVA dataframe for downstream forecasting utilities."""

  missing = [name for name in _required_columns(columns) if name not in df.columns]
  if missing:
    raise ValueError(f"Missing OHLCVA columns: {missing}")

  frame = df.copy()
  frame[columns.time] = _parse_timestamp_series(frame[columns.time])
  if frame[columns.time].isna().any():
    raise ValueError(f"Column {columns.time!r} contains invalid timestamps.")

  numeric_cols = [
    columns.open,
    columns.high,
    columns.low,
    columns.close,
    columns.volume,
  ]
  if columns.amount is not None:
    numeric_cols.append(columns.amount)

  for col in numeric_cols:
    frame[col] = pd.to_numeric(frame[col], errors="coerce")
    if frame[col].isna().any():
      raise ValueError(f"Column {col!r} contains non-numeric or missing values.")

  duplicate_mask = frame.duplicated([columns.symbol, columns.time], keep=False)
  if duplicate_mask.any():
    duplicates = frame.loc[duplicate_mask, [columns.symbol, columns.time]].head(5)
    raise ValueError(
      "Duplicate symbol/timestamp rows found. Example rows:\n"
      f"{duplicates.to_string(index=False)}"
    )

  frame = frame.sort_values([columns.symbol, columns.time]).reset_index(drop=True)
  return frame


def _safe_log(values: pd.Series, name: str) -> pd.Series:
  if (values <= 0).any():
    raise ValueError(f"Target {name!r} requires strictly positive values.")
  return np.log(values)


def make_target_series(
  frame: pd.DataFrame,
  columns: OHLCVAColumns,
  target: FinancialTarget,
) -> pd.DataFrame:
  """Maps OHLCVA bars to a single target series suitable for TimesFM."""

  close = frame[columns.close].astype(float)
  open_ = frame[columns.open].astype(float)
  high = frame[columns.high].astype(float)
  low = frame[columns.low].astype(float)
  volume = frame[columns.volume].astype(float)

  if target == "close":
    values = close
  elif target == "log_close":
    values = _safe_log(close, target)
  elif target == "close_return":
    values = close.pct_change()
  elif target == "log_close_return":
    values = _safe_log(close, "close").diff()
  elif target == "hlc3":
    values = (high + low + close) / 3.0
  elif target == "ohlc4":
    values = (open_ + high + low + close) / 4.0
  elif target == "volume":
    values = volume
  elif target == "log_volume":
    values = _safe_log(volume, target)
  elif target == "vwap":
    if columns.amount is None:
      raise ValueError("Target 'vwap' requires an amount column.")
    amount = frame[columns.amount].astype(float)
    if (volume <= 0).any():
      raise ValueError("Target 'vwap' requires strictly positive volume.")
    values = amount / volume
  else:
    raise ValueError(f"Unsupported financial target: {target}")

  target_frame = pd.DataFrame(
    {
      columns.time: frame[columns.time].to_numpy(),
      "target": values.to_numpy(dtype=np.float32),
    }
  )
  target_frame = target_frame.replace([np.inf, -np.inf], np.nan).dropna().reset_index(
    drop=True
  )
  return target_frame


def infer_frequency(timestamps: pd.DatetimeIndex) -> str:
  """Infers a reasonable pandas frequency string for a sorted datetime index."""

  if len(timestamps) < 2:
    raise ValueError("At least two timestamps are required to infer frequency.")

  freq = pd.infer_freq(timestamps)
  if freq is not None:
    return freq

  deltas = timestamps.to_series().diff().dropna()
  if deltas.empty:
    raise ValueError("Failed to infer frequency from timestamps.")

  median_delta = deltas.median()
  if pd.isna(median_delta) or median_delta <= pd.Timedelta(0):
    raise ValueError("Failed to infer a positive frequency from timestamps.")

  return pd.tseries.frequencies.to_offset(median_delta).freqstr


def extend_time_index(
  context_timestamps: pd.DatetimeIndex,
  horizon: int,
  frequency: str | None = None,
) -> tuple[pd.DatetimeIndex, str]:
  """Extends a context index into the forecast horizon."""

  if horizon <= 0:
    raise ValueError("horizon must be positive.")
  if len(context_timestamps) == 0:
    raise ValueError("context_timestamps must be non-empty.")

  freq = frequency or infer_frequency(context_timestamps)
  offset = pd.tseries.frequencies.to_offset(freq)
  future = pd.date_range(
    start=context_timestamps[-1] + offset,
    periods=horizon,
    freq=offset,
  )
  return future, offset.freqstr


def build_calendar_covariates(
  timestamps: pd.DatetimeIndex,
) -> tuple[dict[str, np.ndarray], dict[str, np.ndarray]]:
  """Creates future-known calendar covariates for XReg."""

  if len(timestamps) == 0:
    raise ValueError("timestamps must be non-empty.")

  time_index = np.linspace(0.0, 1.0, len(timestamps), dtype=np.float32)
  dynamic_numerical_covariates = {
    "time_index": time_index,
    "is_month_start": timestamps.is_month_start.astype(np.float32),
    "is_month_end": timestamps.is_month_end.astype(np.float32),
    "is_quarter_end": timestamps.is_quarter_end.astype(np.float32),
  }

  iso = timestamps.isocalendar()
  dynamic_categorical_covariates = {
    "day_of_week": timestamps.dayofweek.to_numpy(dtype=np.int32),
    "week_of_year": iso.week.to_numpy(dtype=np.int32),
    "month_of_year": timestamps.month.to_numpy(dtype=np.int32),
  }

  intraday = any(
    value != 0
    for value in (
      timestamps.hour.max(),
      timestamps.minute.max(),
      timestamps.second.max(),
    )
  )
  if intraday:
    dynamic_categorical_covariates["hour_of_day"] = timestamps.hour.to_numpy(
      dtype=np.int32
    )
    dynamic_categorical_covariates["minute_of_hour"] = timestamps.minute.to_numpy(
      dtype=np.int32
    )

  return dynamic_numerical_covariates, dynamic_categorical_covariates


def target_is_nonnegative(target: FinancialTarget) -> bool:
  """Whether a target should be clamped to non-negative outputs."""

  return target in {"close", "log_close", "hlc3", "ohlc4", "volume", "log_volume", "vwap"}


def target_supports_directional_accuracy(target: FinancialTarget) -> bool:
  """Whether directional accuracy should be computed on target levels directly."""

  return target in {"close_return", "log_close_return"}


def build_last_window_tasks(
  df: pd.DataFrame,
  columns: OHLCVAColumns,
  target: FinancialTarget,
  horizon: int,
  context_length: int,
  min_context: int = 32,
) -> PreparedTaskCollection:
  """Builds one forecast task per symbol using the latest available context."""

  if context_length <= 0:
    raise ValueError("context_length must be positive.")

  tasks: list[PreparedTask] = []
  skipped_symbols: dict[str, str] = {}
  frame = validate_ohlcva_frame(df, columns)

  for symbol, group in frame.groupby(columns.symbol, sort=False):
    target_frame = make_target_series(group, columns, target)
    if len(target_frame) < min_context:
      skipped_symbols[str(symbol)] = (
        f"only {len(target_frame)} target points after preprocessing; need {min_context}"
      )
      continue

    trimmed = target_frame.tail(context_length).reset_index(drop=True)
    context_timestamps = pd.DatetimeIndex(trimmed[columns.time])
    future_timestamps, frequency = extend_time_index(context_timestamps, horizon)
    all_timestamps = context_timestamps.append(future_timestamps)
    dyn_num, dyn_cat = build_calendar_covariates(all_timestamps) # TODO 这里是 timesFm模型需要吗？

    static_categorical_covariates: dict[str, int | str] = {"symbol": str(symbol)}
    if columns.exchange is not None:
      static_categorical_covariates["exchange"] = str(group[columns.exchange].iloc[-1])

    tasks.append(
      PreparedTask(
        symbol=str(symbol),
        target_name=target,
        cutoff_time=context_timestamps[-1],
        context_values=trimmed["target"].to_numpy(dtype=np.float32),
        context_timestamps=context_timestamps,
        future_timestamps=future_timestamps,
        future_values=None,
        dynamic_numerical_covariates=dyn_num,
        dynamic_categorical_covariates=dyn_cat,
        static_numerical_covariates={},
        static_categorical_covariates=static_categorical_covariates,
        frequency=frequency,
      )
    )

  return PreparedTaskCollection(tasks=tasks, skipped_symbols=skipped_symbols)


def build_walk_forward_tasks(
  df: pd.DataFrame,
  columns: OHLCVAColumns,
  target: FinancialTarget,
  horizon: int,
  context_length: int,
  stride: int | None = None,
  min_context: int = 32,
) -> PreparedTaskCollection:
  """Builds rolling backtest tasks across all symbols."""

  if horizon <= 0:
    raise ValueError("horizon must be positive.")
  if context_length <= 0:
    raise ValueError("context_length must be positive.")

  walk_stride = stride or horizon
  tasks: list[PreparedTask] = []
  skipped_symbols: dict[str, str] = {}
  frame = validate_ohlcva_frame(df, columns)

  for symbol, group in frame.groupby(columns.symbol, sort=False):
    target_frame = make_target_series(group, columns, target)
    if len(target_frame) < min_context + horizon:
      skipped_symbols[str(symbol)] = (
        f"only {len(target_frame)} target points after preprocessing; need at least "
        f"{min_context + horizon} for walk-forward evaluation"
      )
      continue

    timestamps = pd.DatetimeIndex(target_frame[columns.time])
    values = target_frame["target"].to_numpy(dtype=np.float32)
    frequency = infer_frequency(timestamps)

    static_categorical_covariates: dict[str, int | str] = {"symbol": str(symbol)}
    if columns.exchange is not None:
      static_categorical_covariates["exchange"] = str(group[columns.exchange].iloc[-1])

    for cutoff in range(min_context, len(values) - horizon + 1, walk_stride):
      context_start = max(0, cutoff - context_length)
      context_values = values[context_start:cutoff]
      if len(context_values) < min_context:
        continue

      context_timestamps = timestamps[context_start:cutoff]
      future_values = values[cutoff : cutoff + horizon]
      future_timestamps = timestamps[cutoff : cutoff + horizon]
      all_timestamps = context_timestamps.append(future_timestamps)
      dyn_num, dyn_cat = build_calendar_covariates(all_timestamps)

      tasks.append(
        PreparedTask(
          symbol=str(symbol),
          target_name=target,
          cutoff_time=context_timestamps[-1],
          context_values=context_values.astype(np.float32),
          context_timestamps=context_timestamps,
          future_timestamps=future_timestamps,
          future_values=future_values.astype(np.float32),
          dynamic_numerical_covariates=dyn_num,
          dynamic_categorical_covariates=dyn_cat,
          static_numerical_covariates={},
          static_categorical_covariates=static_categorical_covariates.copy(),
          frequency=frequency,
        )
      )

  return PreparedTaskCollection(tasks=tasks, skipped_symbols=skipped_symbols)


def build_task_collection(
  *,
  df: pd.DataFrame,
  columns: OHLCVAColumns,
  target: FinancialTarget,
  horizon: int,
  context_length: int,
  mode: Literal["forecast", "backtest"] = "backtest",
  stride: int | None = None,
  min_context: int = 128,
) -> PreparedTaskCollection:
  """Builds a task collection for either forecast or backtest mode."""

  if mode == "forecast":
    return build_last_window_tasks(
      df=df,
      columns=columns,
      target=target,
      horizon=horizon,
      context_length=context_length,
      min_context=min_context,
    )
  if mode == "backtest":
    return build_walk_forward_tasks(
      df=df,
      columns=columns,
      target=target,
      horizon=horizon,
      context_length=context_length,
      stride=stride,
      min_context=min_context,
    )
  raise ValueError(f"Unsupported mode: {mode}")


def filter_tasks_by_eval_range(
  prepared: PreparedTaskCollection,
  *,
  eval_start: str | pd.Timestamp | None = None,
  eval_end: str | pd.Timestamp | None = None,
) -> PreparedTaskCollection:
  """Filters prepared tasks by inclusive cutoff date boundaries."""

  if eval_start is None and eval_end is None:
    return prepared

  start_ts = pd.Timestamp(eval_start) if eval_start is not None else None
  end_ts = pd.Timestamp(eval_end) if eval_end is not None else None
  filtered_tasks = [
    task
    for task in prepared.tasks
    if (start_ts is None or task.cutoff_time >= start_ts)
    and (end_ts is None or task.cutoff_time <= end_ts)
  ]
  return PreparedTaskCollection(
    tasks=filtered_tasks,
    skipped_symbols=prepared.skipped_symbols,
  )


def collate_timesfm_inputs(tasks: list[PreparedTask]) -> dict[str, Any]:
  """Converts prepared tasks into TimesFM `forecast_with_covariates` inputs."""

  if not tasks:
    raise ValueError("tasks must be non-empty.")

  dynamic_numerical_covariates: dict[str, list[np.ndarray]] = {}
  dynamic_categorical_covariates: dict[str, list[np.ndarray]] = {}
  static_numerical_covariates: dict[str, list[float]] = {}
  static_categorical_covariates: dict[str, list[int | str]] = {}

  numerical_keys = sorted(tasks[0].dynamic_numerical_covariates.keys())
  categorical_keys = sorted(tasks[0].dynamic_categorical_covariates.keys())
  static_num_keys = sorted(tasks[0].static_numerical_covariates.keys())
  static_cat_keys = sorted(tasks[0].static_categorical_covariates.keys())

  for task in tasks:
    if sorted(task.dynamic_numerical_covariates.keys()) != numerical_keys:
      raise ValueError("All tasks must share the same dynamic numerical covariates.")
    if sorted(task.dynamic_categorical_covariates.keys()) != categorical_keys:
      raise ValueError("All tasks must share the same dynamic categorical covariates.")
    if sorted(task.static_numerical_covariates.keys()) != static_num_keys:
      raise ValueError("All tasks must share the same static numerical covariates.")
    if sorted(task.static_categorical_covariates.keys()) != static_cat_keys:
      raise ValueError("All tasks must share the same static categorical covariates.")

  for name in numerical_keys:
    dynamic_numerical_covariates[name] = [
      task.dynamic_numerical_covariates[name].astype(np.float32) for task in tasks
    ]
  for name in categorical_keys:
    dynamic_categorical_covariates[name] = [
      task.dynamic_categorical_covariates[name].astype(np.int32) for task in tasks
    ]
  for name in static_num_keys:
    static_numerical_covariates[name] = [
      float(task.static_numerical_covariates[name]) for task in tasks
    ]
  for name in static_cat_keys:
    static_categorical_covariates[name] = [
      task.static_categorical_covariates[name] for task in tasks
    ]

  return {
    "inputs": [task.context_values.astype(np.float32) for task in tasks],
    "dynamic_numerical_covariates": dynamic_numerical_covariates or None,
    "dynamic_categorical_covariates": dynamic_categorical_covariates or None,
    "static_numerical_covariates": static_numerical_covariates or None,
    "static_categorical_covariates": static_categorical_covariates or None,
  }


def _flatten_actuals(tasks: list[PreparedTask]) -> np.ndarray:
  values = [
    task.future_values.astype(np.float32)
    for task in tasks
    if task.future_values is not None
  ]
  if not values:
    raise ValueError("All tasks must contain future_values for evaluation.")
  return np.concatenate(values, axis=0)


def compute_forecast_metrics(
  tasks: list[PreparedTask],
  point_forecast: np.ndarray,
  quantile_forecast: np.ndarray | None = None,
) -> dict[str, Any]:
  """Computes aggregate financial forecasting metrics."""

  if len(tasks) == 0:
    raise ValueError("tasks must be non-empty.")
  if point_forecast.shape[0] != len(tasks):
    raise ValueError("point_forecast batch size must match tasks.")
  if any(task.future_values is None for task in tasks):
    raise ValueError("All tasks must contain future_values for evaluation.")

  actual = _flatten_actuals(tasks)
  forecast = point_forecast.reshape(-1)
  error = forecast - actual
  abs_actual = np.abs(actual)
  abs_forecast = np.abs(forecast)
  smape_denom = abs_actual + abs_forecast

  metrics: dict[str, Any] = {
    "task_count": len(tasks),
    "point_count": int(actual.size),
    "mae": float(np.mean(np.abs(error))),
    "rmse": float(np.sqrt(np.mean(np.square(error)))),
    "wape": float(np.sum(np.abs(error)) / max(np.sum(abs_actual), 1e-8)),
    "smape": float(
      np.mean(
        np.where(smape_denom > 1e-8, 2.0 * np.abs(error) / smape_denom, 0.0)
      )
    ),
  }

  target_name = tasks[0].target_name
  direction_hits = []
  for task, prediction in zip(tasks, point_forecast, strict=True):
    truth = task.future_values
    if truth is None:
      continue
    if target_supports_directional_accuracy(target_name):
      direction_hits.append(np.sign(prediction) == np.sign(truth))
      continue
    anchor = np.array([task.context_values[-1]], dtype=np.float32)
    pred_delta = np.diff(np.concatenate([anchor, prediction.astype(np.float32)]))
    true_delta = np.diff(np.concatenate([anchor, truth.astype(np.float32)]))
    direction_hits.append(np.sign(pred_delta) == np.sign(true_delta))

  if direction_hits:
    metrics["directional_accuracy"] = float(np.mean(np.concatenate(direction_hits)))

  if quantile_forecast is not None:
    flattened_quantiles = quantile_forecast.reshape(-1, quantile_forecast.shape[-1])
    q10 = flattened_quantiles[:, 1]
    q20 = flattened_quantiles[:, 2]
    q80 = flattened_quantiles[:, 8]
    q90 = flattened_quantiles[:, 9]
    metrics["coverage_80"] = float(np.mean((actual >= q20) & (actual <= q80)))
    metrics["coverage_90"] = float(np.mean((actual >= q10) & (actual <= q90)))

  per_symbol = {}
  start = 0
  for task, prediction in zip(tasks, point_forecast, strict=True):
    truth = task.future_values
    if truth is None:
      continue
    symbol = task.symbol
    end = start + len(truth)
    symbol_forecast = forecast[start:end]
    symbol_truth = actual[start:end]
    symbol_error = symbol_forecast - symbol_truth
    block = per_symbol.setdefault(symbol, {"point_count": 0, "abs_error_sum": 0.0, "sq_error_sum": 0.0})
    block["point_count"] += int(len(truth))
    block["abs_error_sum"] += float(np.sum(np.abs(symbol_error)))
    block["sq_error_sum"] += float(np.sum(np.square(symbol_error)))
    start = end

  metrics["per_symbol"] = {
    symbol: {
      "point_count": block["point_count"],
      "mae": block["abs_error_sum"] / block["point_count"],
      "rmse": float(np.sqrt(block["sq_error_sum"] / block["point_count"])),
    }
    for symbol, block in per_symbol.items()
  }
  return metrics


def add_experiment_splits(
  forecast_frame: pd.DataFrame,
  *,
  train_start: str = "2025-06-01",
  train_end: str = "2025-11-30",
  val_start: str = "2025-12-01",
  val_end: str = "2025-12-31",
  test_start: str = "2026-01-01",
  test_end: str = "2026-02-28",
  date_column: str = "context_end_date",
) -> pd.DataFrame:
  """Assigns train/val/test split labels using the experiment protocol."""

  if date_column not in forecast_frame.columns:
    raise ValueError(f"Missing date column for split assignment: {date_column!r}")

  frame = forecast_frame.copy()
  frame[date_column] = pd.to_datetime(frame[date_column], errors="raise")
  frame["split"] = "out_of_range"

  for split_name, start, end in (
    ("train", train_start, train_end),
    ("val", val_start, val_end),
    ("test", test_start, test_end),
  ):
    mask = frame[date_column].between(pd.Timestamp(start), pd.Timestamp(end))
    frame.loc[mask, "split"] = split_name

  return frame


def _safe_correlation(
  left: pd.Series,
  right: pd.Series,
  *,
  method: Literal["pearson", "spearman"],
) -> float | None:
  if len(left) < 2 or len(right) < 2:
    return None
  if method == "spearman":
    left = left.rank(method="average")
    right = right.rank(method="average")
    method = "pearson"
  value = left.corr(right, method=method)
  if pd.isna(value):
    return None
  return float(value)


def _safe_mean(values: pd.Series) -> float | None:
  clean = values.dropna()
  if clean.empty:
    return None
  return float(clean.mean())


def _safe_information_ratio(values: pd.Series) -> float | None:
  clean = values.dropna().to_numpy(dtype=np.float64)
  if clean.size == 0:
    return None
  sigma = float(np.std(clean))
  if sigma <= _RETURN_EPS:
    return None
  return float(np.mean(clean) / sigma)


def compute_cross_sectional_metrics(
  forecast_frame: pd.DataFrame,
  *,
  top_k: int = 20,
  splits: Sequence[str] = ("val", "test"),
) -> tuple[pd.DataFrame, dict[str, Any]]:
  """Computes daily and aggregated cross-sectional return metrics."""

  if top_k <= 0:
    raise ValueError("top_k must be positive.")

  required_columns = {
    "instrument",
    "context_end_date",
    "target_end_date",
    "horizon",
    "pred_return",
    "true_return",
    "split",
  }
  missing = sorted(required_columns - set(forecast_frame.columns))
  if missing:
    raise ValueError(
      "forecast_frame is missing required columns for cross-sectional metrics: "
      f"{missing}"
    )

  frame = forecast_frame.copy()
  frame["context_end_date"] = pd.to_datetime(frame["context_end_date"], errors="raise")
  frame["target_end_date"] = pd.to_datetime(frame["target_end_date"], errors="raise")
  frame = frame[frame["split"].isin(set(splits))].copy()
  frame = frame.dropna(subset=["pred_return", "true_return"])

  daily_rows = []
  for (split_name, horizon, context_end_date), group in frame.groupby(
    ["split", "horizon", "context_end_date"],
    sort=True,
  ):
    group = group.sort_values("pred_return", ascending=False).reset_index(drop=True)
    cross_section_size = len(group)
    if cross_section_size == 0:
      continue

    k = min(top_k, cross_section_size)
    bottom_group = group.sort_values("pred_return", ascending=True).head(k)
    top_group = group.head(k)
    ic = _safe_correlation(group["pred_return"], group["true_return"], method="pearson")
    rank_ic = _safe_correlation(
      group["pred_return"],
      group["true_return"],
      method="spearman",
    )

    daily_rows.append(
      {
        "split": split_name,
        "horizon": int(horizon),
        "context_end_date": context_end_date,
        "cross_section_size": int(cross_section_size),
        "top_k": int(k),
        "ic": ic,
        "rank_ic": rank_ic,
        "top_k_return": float(top_group["true_return"].mean()),
        "bottom_k_return": float(bottom_group["true_return"].mean()),
        "long_short_return": float(
          top_group["true_return"].mean() - bottom_group["true_return"].mean()
        ),
      }
    )

  daily_metrics = pd.DataFrame(daily_rows)

  summary_rows = []
  if not daily_metrics.empty:
    for (split_name, horizon), group in daily_metrics.groupby(["split", "horizon"], sort=True):
      sample_frame = frame[
        (frame["split"] == split_name) & (frame["horizon"] == horizon)
      ].copy()
      mae_return = float(
        np.mean(np.abs(sample_frame["pred_return"] - sample_frame["true_return"]))
      )
      mae_close = None
      if {"pred_close", "true_close"}.issubset(sample_frame.columns):
        mae_close = float(
          np.mean(np.abs(sample_frame["pred_close"] - sample_frame["true_close"]))
        )

      summary_rows.append(
        {
          "split": split_name,
          "horizon": int(horizon),
          "sample_count": int(len(sample_frame)),
          "date_count": int(len(group)),
          "instrument_count": int(sample_frame["instrument"].nunique()),
          "mean_ic": _safe_mean(group["ic"]),
          "mean_rank_ic": _safe_mean(group["rank_ic"]),
          "ic_ir": _safe_information_ratio(group["ic"]),
          "rank_ic_ir": _safe_information_ratio(group["rank_ic"]),
          "topk_mean_return": float(group["top_k_return"].mean()),
          "bottomk_mean_return": float(group["bottom_k_return"].mean()),
          "long_short_topk_mean_return": float(group["long_short_return"].mean()),
          "mae_return": mae_return,
          "mae_close": mae_close,
        }
      )

  return daily_metrics, {"top_k": int(top_k), "rows": summary_rows}


def apply_experiment_split_mode(
  forecast_frame: pd.DataFrame,
  *,
  split_mode: Literal["protocol", "all"] = "protocol",
  train_start: str = "2025-06-01",
  train_end: str = "2025-11-30",
  val_start: str = "2025-12-01",
  val_end: str = "2025-12-31",
  test_start: str = "2026-01-01",
  test_end: str = "2026-02-28",
) -> pd.DataFrame:
  """Applies either protocol splits or a single all-split tag."""

  if split_mode == "protocol":
    return add_experiment_splits(
      forecast_frame,
      train_start=train_start,
      train_end=train_end,
      val_start=val_start,
      val_end=val_end,
      test_start=test_start,
      test_end=test_end,
    )
  if split_mode == "all":
    tagged = forecast_frame.copy()
    tagged["split"] = "all"
    return tagged
  raise ValueError(f"Unsupported split_mode: {split_mode}")


def build_backtest_metrics_payload(
  *,
  tasks: list[PreparedTask],
  point_forecast: np.ndarray,
  quantile_forecast: np.ndarray | None,
  forecast_frame: pd.DataFrame,
  target: FinancialTarget,
  split_mode: Literal["protocol", "all"],
  eval_start: str | None,
  eval_end: str | None,
  train_start: str,
  train_end: str,
  val_start: str,
  val_end: str,
  test_start: str,
  test_end: str,
  top_k: int,
  splits: Sequence[str],
) -> tuple[dict[str, Any], pd.DataFrame | None]:
  """Builds the shared metrics payload for zero-shot backtests."""

  metrics_payload = {
    "point_metrics": compute_forecast_metrics(
      tasks=tasks,
      point_forecast=point_forecast,
      quantile_forecast=quantile_forecast,
    ),
    "experiment_protocol": {
      "split_mode": split_mode,
      "eval_start": eval_start,
      "eval_end": eval_end,
      "train_start": train_start,
      "train_end": train_end,
      "val_start": val_start,
      "val_end": val_end,
      "test_start": test_start,
      "test_end": test_end,
      "top_k": top_k,
    },
  }

  if target != "close":
    return metrics_payload, None

  daily_metrics, cross_sectional_summary = compute_cross_sectional_metrics(
    forecast_frame,
    top_k=top_k,
    splits=tuple(splits),
  )
  metrics_payload["cross_sectional_summary"] = cross_sectional_summary
  return metrics_payload, daily_metrics


def flatten_forecast_frame(
  tasks: list[PreparedTask],
  point_forecast: np.ndarray,
  quantile_forecast: np.ndarray | None = None,
) -> pd.DataFrame:
  """Flattens forecast tensors into a row-wise dataframe."""

  if len(tasks) == 0:
    raise ValueError("tasks must be non-empty.")
  if point_forecast.shape[0] != len(tasks):
    raise ValueError("point_forecast batch size must match tasks.")

  rows = []
  for task_index, (task, prediction) in enumerate(zip(tasks, point_forecast, strict=True)):
    quantiles = quantile_forecast[task_index] if quantile_forecast is not None else None
    actual_values = task.future_values
    anchor_value = float(task.context_values[-1])
    for step, (forecast_time, point_value) in enumerate(
      zip(task.future_timestamps, prediction, strict=True),
      start=1,
    ):
      row = {
        "task_id": task_index,
        "symbol": task.symbol,
        "instrument": task.symbol,
        "target": task.target_name,
        "frequency": task.frequency,
        "cutoff_time": task.cutoff_time,
        "context_end_date": task.cutoff_time,
        "forecast_time": forecast_time,
        "target_end_date": forecast_time,
        "step": step,
        "horizon": step,
        "context_length": len(task.context_values),
        "anchor_value": anchor_value,
        "point_forecast": float(point_value),
      }
      if actual_values is not None:
        row["actual"] = float(actual_values[step - 1])
      if task.target_name == "close":
        row["anchor_close"] = anchor_value
        row["pred_close"] = float(point_value)
        if abs(anchor_value) > _RETURN_EPS:
          row["pred_return"] = float(point_value / anchor_value - 1.0)
        else:
          row["pred_return"] = np.nan
        if actual_values is not None:
          actual_value = float(actual_values[step - 1])
          row["true_close"] = actual_value
          if abs(anchor_value) > _RETURN_EPS:
            row["true_return"] = float(actual_value / anchor_value - 1.0)
          else:
            row["true_return"] = np.nan
      if quantiles is not None:
        row["mean"] = float(quantiles[step - 1, 0])
        row["q10"] = float(quantiles[step - 1, 1])
        row["q50"] = float(quantiles[step - 1, 5])
        row["q90"] = float(quantiles[step - 1, 9])
      rows.append(row)
  return pd.DataFrame(rows)


def flatten_predictions(
  tasks: list[PreparedTask],
  point_forecast: np.ndarray,
  quantile_forecast: np.ndarray | None = None,
) -> pd.DataFrame:
  """Generic wrapper name for shared zero-shot runners."""

  return flatten_forecast_frame(
    tasks=tasks,
    point_forecast=point_forecast,
    quantile_forecast=quantile_forecast,
  )


def enforce_ohlc_constraints(
  forecasts: dict[str, np.ndarray],
) -> dict[str, np.ndarray]:
  """Post-processes independently forecast OHLCVA components into valid bars."""

  result = {name: np.asarray(values, dtype=np.float32).copy() for name, values in forecasts.items()}

  required_price_keys = {"open", "high", "low", "close"}
  if required_price_keys.issubset(result):
    open_ = result["open"]
    high = result["high"]
    low = result["low"]
    close = result["close"]
    upper = np.maximum(open_, close)
    lower = np.minimum(open_, close)
    result["high"] = np.maximum(high, upper)
    result["low"] = np.minimum(low, lower)

  for nonnegative_key in ("volume", "amount"):
    if nonnegative_key in result:
      result[nonnegative_key] = np.maximum(result[nonnegative_key], 0.0)

  return result


def _json_ready(value: Any) -> Any:
  if isinstance(value, (pd.Timestamp, np.datetime64)):
    return str(value)
  if pd.isna(value):
    return None
  return value


def materialize_zero_shot_layout(
  *,
  run_dir: str | Path,
  forecast_frame: pd.DataFrame,
  metrics_payload: dict[str, Any],
  run_name: str,
  model_id: str,
  target: str,
  context_length: int,
  horizon: int,
  top_k: int,
  xreg: str,
  daily_metrics_frame: pd.DataFrame | None = None,
  source_predictions_path: str | Path | None = None,
  source_daily_metrics_path: str | Path | None = None,
  source_metrics_path: str | Path | None = None,
  splits: Sequence[str] = ("val", "test"),
) -> None:
  """Writes a Kronos-like zero-shot directory layout for TimesFM outputs."""

  if "split" not in forecast_frame.columns:
    raise ValueError("forecast_frame must contain a 'split' column.")

  target_dir = Path(run_dir)
  target_dir.mkdir(parents=True, exist_ok=True)
  split_names = [str(name) for name in splits]
  summary_rows = metrics_payload.get("cross_sectional_summary", {}).get("rows", [])
  daily_frame = (
    daily_metrics_frame.copy()
    if daily_metrics_frame is not None
    else pd.DataFrame(columns=["split"])
  )

  run_config = {
    "run_name": run_name,
    "model": "TimesFM_2p5_200M_torch",
    "model_id": model_id,
    "target": target,
    "context_length": int(context_length),
    "horizon": int(horizon),
    "top_k": int(top_k),
    "xreg": xreg,
    "source_predictions": (
      str(Path(source_predictions_path).resolve())
      if source_predictions_path is not None
      else None
    ),
    "source_daily_metrics": (
      str(Path(source_daily_metrics_path).resolve())
      if source_daily_metrics_path is not None
      else None
    ),
    "source_metrics": (
      str(Path(source_metrics_path).resolve())
      if source_metrics_path is not None
      else None
    ),
    "splits": split_names,
    "experiment_protocol": metrics_payload.get("experiment_protocol", {}),
  }
  (target_dir / "run_config.json").write_text(
    json.dumps(run_config, indent=2, default=str),
    encoding="utf-8",
  )

  for split_name in split_names:
    split_dir = target_dir / split_name
    split_dir.mkdir(parents=True, exist_ok=True)

    split_predictions = forecast_frame[forecast_frame["split"] == split_name].copy()
    split_daily = daily_frame[daily_frame["split"] == split_name].copy()
    split_summary = next(
      (
        row
        for row in summary_rows
        if row.get("split") == split_name and int(row.get("horizon", -1)) == int(horizon)
      ),
      None,
    )

    split_predictions.to_csv(split_dir / "predictions.csv", index=False)
    split_daily.to_csv(split_dir / "daily_metrics.csv", index=False)

    split_metrics = {
      "run_name": run_name,
      "split": split_name,
      "model": "TimesFM_2p5_200M_torch",
      "model_id": model_id,
      "target": target,
      "context_length": int(context_length),
      "horizon": int(horizon),
      "top_k": int(top_k),
      "xreg": xreg,
      "prediction_rows": int(len(split_predictions)),
      "daily_metric_rows": int(len(split_daily)),
      "summary": (
        {key: _json_ready(value) for key, value in split_summary.items()}
        if split_summary is not None
        else None
      ),
    }
    (split_dir / "metrics.json").write_text(
      json.dumps(split_metrics, indent=2, default=str),
      encoding="utf-8",
    )


def materialize_stage1_layout(
  *,
  run_dir: str | Path,
  forecast_frame: pd.DataFrame,
  metrics_payload: dict[str, Any],
  run_name: str,
  model_id: str,
  target: str,
  context_length: int,
  horizon: int,
  top_k: int,
  xreg: str,
  daily_metrics_frame: pd.DataFrame | None = None,
  source_predictions_path: str | Path | None = None,
  source_daily_metrics_path: str | Path | None = None,
  source_metrics_path: str | Path | None = None,
  splits: Sequence[str] = ("val", "test"),
) -> None:
  """Compatibility wrapper for the old stage1 name."""

  materialize_zero_shot_layout(
    run_dir=run_dir,
    forecast_frame=forecast_frame,
    metrics_payload=metrics_payload,
    run_name=run_name,
    model_id=model_id,
    target=target,
    context_length=context_length,
    horizon=horizon,
    top_k=top_k,
    xreg=xreg,
    daily_metrics_frame=daily_metrics_frame,
    source_predictions_path=source_predictions_path,
    source_daily_metrics_path=source_daily_metrics_path,
    source_metrics_path=source_metrics_path,
    splits=splits,
  )


def materialize_run_layout(
  *,
  run_dir: str | Path,
  forecast_frame: pd.DataFrame,
  metrics_payload: dict[str, Any],
  run_name: str,
  model_id: str,
  target: str,
  context_length: int,
  horizon: int,
  top_k: int,
  xreg: str,
  daily_metrics_frame: pd.DataFrame | None = None,
  source_predictions_path: str | Path | None = None,
  source_daily_metrics_path: str | Path | None = None,
  source_metrics_path: str | Path | None = None,
  splits: Sequence[str] = ("val", "test"),
) -> None:
  """Generic wrapper name for shared zero-shot layout materialization."""

  materialize_zero_shot_layout(
    run_dir=run_dir,
    forecast_frame=forecast_frame,
    metrics_payload=metrics_payload,
    run_name=run_name,
    model_id=model_id,
    target=target,
    context_length=context_length,
    horizon=horizon,
    top_k=top_k,
    xreg=xreg,
    daily_metrics_frame=daily_metrics_frame,
    source_predictions_path=source_predictions_path,
    source_daily_metrics_path=source_daily_metrics_path,
    source_metrics_path=source_metrics_path,
    splits=splits,
  )
